GET http://localhost:3000/api/message/
Content-Type: application/json

{

}

###

POST http://localhost:3000/api/message/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGViZjNjOTc4YTE3YWRmMTdjMjA4MyIsImlhdCI6MTc1OTY3MjIzMywiZXhwIjoxNzU5NjcyMjYzfQ.S4JV_1sMzpCn-goSYynP9ksOoFa6KuxqJLOIlJOszeE

{
    "content": "Hey there!",
    "senderId": "21",
    "receiverId": "32"
}